ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_type VARCHAR(16) NOT NULL DEFAULT 'ONE_TIME';
ALTER TABLE trips ADD COLUMN IF NOT EXISTS publish_at DATETIME NULL;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;
